#!/usr/bin/env bash

# build containers
docker build --file=docker/services/varnish/Dockerfile --tag=alcohol/pastebin-varnish:latest .
docker build --file=docker/services/nginx/Dockerfile --tag=alcohol/pastebin-nginx:latest .
docker build --file=docker/services/php-fpm/Dockerfile.dist --tag=alcohol/pastebin-fpm:latest --build-arg=RELEASE=$(git rev-parse --short ${TRAVIS_COMMIT}) .

# log in
echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin

# push tagged containers
docker push alcohol/pastebin-varnish:latest
docker push alcohol/pastebin-nginx:latest
docker push alcohol/pastebin-fpm:latest

# log out
docker logout
