#!/bin/sh

set -e

echo "Starting varnish logger"
(
  varnishncsa -a -w /dev/stdout ; \
  pkill varnishd # kill varnishd if varnishncsa exits for whatever reason
) &

echo "Starting varnish daemon"
exec varnishd -F \
  -f ${VARNISH_CONFIG} \
  -s default,${VARNISH_CACHE_SIZE} \
  -a ${VARNISH_IP}:${VARNISH_PORT} \
  -T ${VARNISH_ADMIN_IP}:${VARNISH_ADMIN_PORT} \
  ${VARNISHD_PARAMS}
