---
name: Continuous Integration

on: [push, pull_request]

jobs:

  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none
          tools: composer, cs2pr, php-cs-fixer
      - run: composer install
      - uses: actions/cache@v2
        with:
          path: .php-cs-fixer.cache
          key: php-cs-fixer
      - if: ${{ github.event_name == 'push' }}
        run: php-cs-fixer fix --diff --dry-run --format=checkstyle | cs2pr
      - if: ${{ github.event_name == 'pull_request' }}
        run: >
          php-cs-fixer fix
          --diff
          --dry-run
          --format=checkstyle
          --path-mode=intersection
          $(git diff --name-only --diff-filter=ACMRTUXB "${COMMIT_RANGE}")
          | cs2pr

  phpstan:
    runs-on: ubuntu-latest
    name: phpstan
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none
          tools: composer, cs2pr, phpstan
      - run: composer install
      - uses: actions/cache@v2
        with:
          path: resultCache.php
          key: phpstan
      - run: phpstan --error-format=checkstyle | cs2pr

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ibiqlik/action-yamllint@v3
        with:
          format: github
